"""Initial migration with v3.0 models

Revision ID: f668079dd3de
Revises: 
Create Date: 2026-07-09 09:11:06.850949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f668079dd3de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_number', sa.String(length=50), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zipcode', sa.String(length=10), nullable=True),
    sa.Column('address_latitude', sa.Float(), nullable=True),
    sa.Column('address_longitude', sa.Float(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('successful_deliveries', sa.Integer(), nullable=True),
    sa.Column('failed_deliveries', sa.Integer(), nullable=True),
    sa.Column('avg_delivery_rating', sa.Float(), nullable=True),
    sa.Column('preferred_delivery_time', sa.String(length=50), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_city', 'customers', ['address_city'], unique=False)
    op.create_index('idx_customers_phone', 'customers', ['phone'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deposits_city', 'deposits', ['city'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('vehicle_capacity_kg', sa.Float(), nullable=True),
    sa.Column('vehicle_capacity_m3', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('completed_deliveries', sa.Integer(), nullable=True),
    sa.Column('failed_deliveries', sa.Integer(), nullable=True),
    sa.Column('avg_delivery_time_minutes', sa.Float(), nullable=True),
    sa.Column('specialty_cities', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drivers_phone', 'drivers', ['phone'], unique=False)
    op.create_index('idx_drivers_status', 'drivers', ['status'], unique=False)
    op.create_table('operational_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('representations', sa.JSON(), nullable=True),
    sa.Column('knowledge', sa.JSON(), nullable=True),
    sa.Column('beliefs', sa.JSON(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.Column('intentions', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('previous_state_id', sa.UUID(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['previous_state_id'], ['operational_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opstates_created', 'operational_states', ['created_at'], unique=False)
    op.create_index('idx_opstates_entity', 'operational_states', ['entity_type', 'entity_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detected_columns', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deposit_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routes_date', 'routes', ['planned_date'], unique=False)
    op.create_index('idx_routes_deposit', 'routes', ['deposit_id'], unique=False)
    op.create_index('idx_routes_driver', 'routes', ['driver_id'], unique=False)
    op.create_index('idx_routes_status', 'routes', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_platform', sa.String(length=50), nullable=True),
    sa.Column('origin_order_id', sa.String(length=100), nullable=True),
    sa.Column('operational_status', sa.String(length=50), nullable=True),
    sa.Column('deposit_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_number', sa.String(length=50), nullable=True),
    sa.Column('address_complement', sa.String(length=100), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zipcode', sa.String(length=10), nullable=True),
    sa.Column('address_latitude', sa.Float(), nullable=True),
    sa.Column('address_longitude', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('declared_value_brl', sa.Float(), nullable=True),
    sa.Column('shipping_cost_brl', sa.Float(), nullable=True),
    sa.Column('promised_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('proof_photo_url', sa.String(length=500), nullable=True),
    sa.Column('proof_signature', sa.Text(), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_city', 'orders', ['address_city'], unique=False)
    op.create_index('idx_orders_customer', 'orders', ['customer_id'], unique=False)
    op.create_index('idx_orders_deposit', 'orders', ['deposit_id'], unique=False)
    op.create_index('idx_orders_driver', 'orders', ['driver_id'], unique=False)
    op.create_index('idx_orders_promised_date', 'orders', ['promised_delivery_date'], unique=False)
    op.create_index('idx_orders_route', 'orders', ['route_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['operational_status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('filters_used', sa.JSON(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('unique_deliverers', sa.Integer(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('operational_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spec_version', sa.String(length=10), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_order', 'operational_events', ['order_id'], unique=False)
    op.create_index('idx_events_processed', 'operational_events', ['processed'], unique=False)
    op.create_index('idx_events_time', 'operational_events', ['time'], unique=False)
    op.create_index('idx_events_type', 'operational_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_type', table_name='operational_events')
    op.drop_index('idx_events_time', table_name='operational_events')
    op.drop_index('idx_events_processed', table_name='operational_events')
    op.drop_index('idx_events_order', table_name='operational_events')
    op.drop_table('operational_events')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_route', table_name='orders')
    op.drop_index('idx_orders_promised_date', table_name='orders')
    op.drop_index('idx_orders_driver', table_name='orders')
    op.drop_index('idx_orders_deposit', table_name='orders')
    op.drop_index('idx_orders_customer', table_name='orders')
    op.drop_index('idx_orders_city', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_routes_status', table_name='routes')
    op.drop_index('idx_routes_driver', table_name='routes')
    op.drop_index('idx_routes_deposit', table_name='routes')
    op.drop_index('idx_routes_date', table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_opstates_entity', table_name='operational_states')
    op.drop_index('idx_opstates_created', table_name='operational_states')
    op.drop_table('operational_states')
    op.drop_index('idx_drivers_status', table_name='drivers')
    op.drop_index('idx_drivers_phone', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('idx_deposits_city', table_name='deposits')
    op.drop_table('deposits')
    op.drop_index('idx_customers_phone', table_name='customers')
    op.drop_index('idx_customers_city', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
